## Step 1. 原始 VCF 转换为 plink2 格式

这一步的目的是将原始压缩 VCF 转换为 plink2 的 `pgen/pvar/psam` 格式，便于后续做样本重命名、样本筛选、LD pruning 和 PCA。

输入文件：
- 原始 VCF：`CIMA_phasing.merged.vcf.gz`

输出文件：
- `CIMA_raw.pgen`
- `CIMA_raw.pvar`
- `CIMA_raw.psam`

说明：
- 这一阶段仍保留原始样本名
- 暂时不做 PCA，不做 GWAS
- 先把基因型数据整理成可操作格式

In [6]:
from pathlib import Path

csv_path = Path("/mnt/zzbnew/peixunban/zhanghebin/CIMA_multiomics_regulation/data/raw/CIMA/Metabolites_and_Lipids/CIMA_Sample_Plasma_Metabolites_and_Lipids_Results.csv")

print("exists:", csv_path.exists())
print("is_file:", csv_path.is_file())
print("size_MB:", round(csv_path.stat().st_size / 1024 / 1024, 2) if csv_path.exists() else None)

exists: True
is_file: True
size_MB: 5.39

In [7]:
import pandas as pd

df = pd.read_csv(csv_path)
print(df.shape)
display(df.head())
print(df.columns.tolist())

(390, 1550)

,sample,O-Phosphoryl-ethanolamine,Acesulfame,Acetic acid,Propanoic acid,Glycolic acid,But-2-enoic acid,Valeric acid,2-Aminoisobutyric acid,L-Alpha-aminobutyric acid,...,PI 20:0-22:6,PI 20:5-22:0,PI 20:4-22:1,PI 20:3-22:2,PI 20:2-22:3,PI 20:1-22:4,PI 20:0-22:5,PI 20:4-22:0,PI 20:3-22:1,PI 20:2-22:2
0,CIMA_H015,1.225213,0.032842,3.455972,4.275737,20.229021,0.062537,0.634065,8.593622,22.512360,...,NaN,11.825791,NaN,15.923843,11.58539,NaN,11.837008,18.987968,30.148115,NaN
1,CIMA_H016,1.272470,0.086072,2.996980,3.598019,18.835006,0.039117,0.566319,9.118566,21.378370,...,NaN,11.376650,24.858793,17.906786,NaN,NaN,NaN,NaN,29.881211,NaN
2,CIMA_H017,1.172774,0.126888,7.860442,3.267677,22.291050,0.055000,0.688793,5.751301,28.211497,...,NaN,NaN,21.264320,12.559251,NaN,NaN,NaN,11.276070,NaN,NaN
3,CIMA_H018,1.618271,0.053564,4.512696,1.991009,15.116417,0.074073,1.124161,5.912626,34.551486,...,11.904203,NaN,38.426573,NaN,NaN,NaN,11.727066,11.178847,NaN,NaN
4,CIMA_H019,1.755173,0.071668,2.400409,4.733403,21.703553,0.094791,0.926420,13.669501,33.472662,...,NaN,NaN,NaN,11.825061,NaN,NaN,NaN,NaN,34.482757,15.030102

['sample', 'O-Phosphoryl-ethanolamine', 'Acesulfame', 'Acetic acid', 'Propanoic acid', 'Glycolic acid', 'But-2-enoic acid', 'Valeric acid', '2-Aminoisobutyric acid', 'L-Alpha-aminobutyric acid', 'alpha-Hydroxyisobutyric acid', '2-Hydroxybutyric acid', '3-Hydroxybutyric acid', 'Acetylglycine', '3-Hydroxyisovaleric acid', '2-Hydroxy-2-methylbutyric acid', '5-Aminoimidazole-4-carboxamide', 'L-Pipecolic acid', '4-Hydroxyproline', 'cis-4-Hydroxy-D-proline', 'Hydroxyisocaproic acid', 'Erythronic acid', '2-Methylbenzoic acid', 'N-Methylnicotinamide', '3,4-Dihydroxybenzaldehyde', '2-Ethylhexanoic acid', '2-Methylheptanoic Acid', '4-Acetamidobutanoic acid', '4-Guanidinobutyric acid', 'N,N-Dimethyl-L-Valine', 'Monomethyl glutaric acid', '3-Methyloxindole', '3,4-Dihydro-2H-1-benzopyran-2-one', 'D-Xylose', 'Hydrocinnamic acid', '2-HYDROXY-4-(METHYLTHIO)BUTANOATE', 'Phenylglyoxylic acid', 'D-Arabinose', '2-Phenylpropionic acid', '2-Phenylglycine', '(S)C(S)S-S-Methylcysteine sulfoxide', '3-Hydroxyphenylacetic acid', 'Mandelic acid', 'Ribitol', '3-Hydroxyanthranilic acid', '3-Aminosalicylic acid', 'Gentisic acid', 'N-Acetylproline', 'Tranexamic Acid', 'Isovalerylglycine', 'Hydroxyoctanoic acid', '2-Indolecarboxylic acid', 'S-Allylcysteine', 'Bicine', '3-Phenylbutyric acid', '2-Deoxyglucose', '4-Hydroxycinnamic acid', 'm-Coumaric acid', 'L-Phenylalanine', 'Phenyllactic acid', 'Desaminotyrosine', 'Arabinonic acid', 'Vanillic acid', 'p-Hydroxymandelic acid', '1-Methylhistidine', 'Decanoic acid', 'beta-Glycerophosphoric acid', 'N-Acetylleucine', 'Shikimic acid', 'Dehydroascorbic acid', 'Glycylvaline', 'L-Arginine', 'L-Gulonolactone', 'Glucosamine', 'D-Glucose', 'L-Sorbose', 'myo-Inositol', 'beta-(m-Hydroxyphenyl)hydracrylic Acid', 'Undecylenic acid', 'Phosphoserine', 'Undecanoic acid', '3-Phosphoglyceric acid', 'Indoleacrylic acid', 'N-Acetylglutamine', 'L-Homoarginine', '10-Hydroxydecanoic acid', '3-Indoleglyoxylic acid', 'N-Acetyl-L-methionine', '4-Aminohippuric acid', 'Ferulic acid', '3-Hydroxyhippuric', 'D-Gluconolactone', 'Gluconic acid', 'Homoveratric acid', 'Selenomethionine', 'N-Acetyl-L-histidine', 'Syringic acid', 'Vanillymandelic Acid', '5Z-Dodecenoic acid', '11-Dodecenoic acid', 'Dodecanoic acid', 'Diethyl oxalpropionate', '3-Indolebutyric acid', 'Indolepyruvate', 'L-Tryptophan', 'Xanthurenic acid', 'L-Kynurenine', 'Glyoxylic acid', '12-Tridecanoic acid', 'Tridecanoic acid', 'N-a-Acetyl-L-arginine', 'Alanylglutamine', 'N-Acetyl-D-glucosamine', 'Oxalic acid', 'Cortisone', 'Myristoleic acid', 'Myristelaidic acid', '3-Nitrotyrosine', 'Myristic acid', '3,4,5-Trimethoxycinnamic acid', "Pyridoxal 5'-phosphate", 'Maleic acid', 'Fumaric acid', 'Palmitoleic acid', 'Palmitelaidic acid', '(7Z)-Hexadecenoic Acid', '23-Nordeoxycholic Acid Methyl Ester', 'Alpha-N-Phenylacetyl-L-glutamine', 'Itaconic acid', 'Ketoleucine', '3-Methyl-2-oxovaleric acid', '2,3-Diphosphoglyceric acid', 'N-Acetyl-L-alanine', 'D-Aspartic acid', 'Inosine', '10Z-Heptadecenoic acid', '7-Ketolithocholic Acid Methyl Ester', 'cis,cis-Muconic acid', 'Urocanic acid', 'Alpha-Linolenic acid', 'Linolelaidic acid', 'Adipic acid', 'Methylglutaric acid', 'Oxoglutaric acid', '2,2-Dimethylsuccinic acid', '3,6-Diketocholanic Acid Ethyl Ester', 'N-Methyl-D-aspartic acid', 'CIS-11-OCTADECENOIC ACID', 'trans-Vaccenic acid', 'Petroselinic acid', 'Citramalic acid', 'Retinal', 'Tartaric acid', '7-Dehydrocholic Acid Methyl Ester', 'Etodolac', 'Aspartame', 'Pimelic acid', '3-Methyladipic acid', '3-Oxoadipic acid', '3,3-Dimethylglutaric acid', 'D-Ribulose', '10Z-Nonadecenoic acid', 'Ricinoleic acid', 'all-trans-Retinoic acid', '12-hydroxystearic acid', 'Phthalic acid', 'Quinolinic acid', '2,6-Pyridinedicarboxylic acid', 'Eicosapentaenoic acid EPA', '8Z,11Z,14Z,17Z-EICOSATETRAENOIC ACID', 'CIS-11,14,17-EICOSATRIENOIC ACID', '8,11,14-Eicosatrienoic acid', 'Menadione', '11C,14C-EICOSADIENOIC ACID', 'NANA', 'N-Acetylornithine', '11Z-Eicosenoic acid', 'Citrulline', 'Ureidosuccinic acid', 'S-Carboxymethyl-L-cysteine', '5beta-CHOLANIC ACID-3alpha, 7beta-DIOL N-(CARBOXYMETHYL)-AMIDE', '4-Hydroxyphenylpyruvic acid', 'Etiadienic Acid', 'Pregnenolone', 'Etienic Acid', '5beta-ANDROSTAN-3alpha-OL-17beta-CARBOXYLIC ACID', '5beta-ANDROSTAN-3beta-OL-17beta-CARBOXYLIC ACID', 'Leucyl-Glycine', "Uridine 5'-monophosphate", 'Kynurenic acid', 'N-carbamoylglutamic Acid', 'Docosahexaenoic acid DHA', 'Cyclic AMP', 'Docosapentaenoic acid DPA', '5beta-CHOLANIC ACID-3alpha, 7alpha, 12alpha-TRIOL N-(CARBOXYMETHYL)-AMIDE', 'Etiadienic Acid Methyl Ester', 'Adrenic acid', '5beta-ANDROSTAN-3-ONE-17beta-CARBOXYLIC ACID METHYL ESTER', '4-ANDROSTEN-17alpha-OL-3-ONE-17beta-CARBOXYLIC ACID', 'Docosatrienoic acid', '13C,16C-DOCOSADIENOIC ACID', 'Erucic acid', '13tr-Docosenoic Acid', 'Isomaltose', 'Melibiose', 'Lactulose', 'Medroxyprogesterone', 'Glucaric acid', 'Galactaric acid', '5beta-CHOLANIC ACID-12alpha-BROMO-3, 11-DIONE METHYL ESTER', 'Cytidine triphosphate', 'Etiadienic Acid 3-Acetate', 'Hydroretrocortine', 'Etienic Acid Acetate', 'Traumatic acid', 'Taurochenodeoxycholic Acid', 'Taurohyodeoxycholic Acid', 'Dodecanedioic acid', '12-Ketolithocholic Acid Benzoate, Methyl Ester', 'Lithocholenic Acid', 'Lithocholic acid', 'ISOALLOLITHOCHOLIC ACID', 'Nordeoxycholic Acid', 'Tauro-omega-Muricholic Acid', 'Taurocholic acid', 'N-acetyltryptophan', 'Malonylcarnitine', '3,6-Diketocholanic Acid', '3,7-Diketocholanic Acid', '12-Ketolithocholic acid', 'Beta-Ursodeoxycholic Acid', 'Beta-Hyodeoxycholic Acid', 'Chenodeoxycholic acid', 'Hyodeoxycholic acid', 'Murocholic acid', 'Ursodeoxycholic acid', 'Tetradecanedioic acid', 'Choleic Acid', '23-Norcholic Acid', 'Dehydrocholic Acid', 'Dioxolithocholic Acid', '7-Dehydrocholic acid', 'Cholic Acid', 'Beta-Muricholic Acid', 'Hyocholic acid', 'Ursocholic Acid', 'Heptacosanoic acid', 'Lithocholic Acid Acetate', 'O-Adipoylcarnitine', 'Oleoylcarnitine', 'Oxoadipic acid', '1,2,3-Propanetricarboxylic acid', 'Glycodeoxycholic acid', 'Glycochenodeoxycholic acid', 'Glycoursodeoxycholic acid', 'Glycohyodeoxycholic Acid', 'Glycodehydrocholic Acid', 'Heneicosanoic acid', 'Citric acid', 'Isocitric acid', '23-Norcholic Acid Diacetate', '23-Nordeoxycholic Acid Diacetate', 'Glycocholic acid', '2-Methylcitric acid', '12-Dehydrocholic Acid Diacetate', 'Dehydrolithocholic acid', 'Taurocyamine', 'Diethyl tartrate', 'Glycine', 'Sarcosine', 'Beta-Alanine', 'L-Alanine', 'Dimethylglycine', 'Gamma-Aminobutyric acid', 'L-Serine', 'L-Proline', 'Cimetidine', '4-Hydroxybenzoic acid', 'Indole-3-carboxaldehyde', 'L-Glutamine', 'L-Lysine', 'L-Methionine', 'Piperine', 'Ortho-Hydroxyphenylacetic acid', 'Protocatechuic acid', 'L-Histidine', 'Edetic Acid', 'Carnitine(C0)', '7-Methylguanosine', 'Hippuric acid', 'Hydroxyphenyllactic acid', 'L-Homocitrulline', '3-Indolepropionic acid', 'Salicyluric acid', 'L-Acetylcarnitine', 'Propionylcarnitine', 'Curcumin', 'Isovelarylcarnitine', 'Alpha-ketoisovaleric acid', 'L-Asparagine', 'Glutaric acid', 'N-Phenylacetylphenylalanine', 'Phenylpyrivic acid', 'N-Acetyl-L-aspartic acid', 'Decanoylcarnitine (C10)', 'Azelaic acid', 'Sebacic acid', 'Lauroylcarnitine', 'Adenosine monophosphate', 'Guanosine monophosphate', 'Myristoylcarnitine', "s-(5'-Adenosyl)-L-homocysteine", 'Palmitoylcarnitine', 'Stearylcarnitine(C18)', 'Betaine', 'D-Xylulose', 'p-Hydroxyphenylacetic acid', 'L-Cysteic acid', 'Apocholic Acid', '5beta-CHOLANIC ACID-3alpha, 7alpha, 12alpha-TRIOL 3-ETHOXYCARBONYL, METHYL ESTER', 'Estriol', 'Glycerol trihexanoate', 'Cer d18:1/22:0', 'Cer d18:1/24:1', 'Cer d18:1/24:0', 'DAG 16:0-16:1', 'DAG 16:0-16:0', 'DAG 16:1-18:4', 'DAG 16:1-18:3', 'DAG 16:1-18:2', 'DAG 16:0-18:3', 'DAG 16:1-18:1', 'DAG 16:0-18:2', 'DAG 16:0-18:1', 'DAG 16:0-18:0', 'DAG 18:1-18:4', 'DAG 18:1-18:3', 'DAG 18:1-18:2', 'DAG 18:0-18:3', 'DAG 18:1-18:1', 'DAG 18:0-18:2', 'DAG 18:0-18:1', 'DAG 18:0-18:0', 'DAG 18:1-20:5', 'DAG 18:1-20:4', 'DAG 18:1-20:3', 'DAG 18:1-20:2', 'DAG 18:1-20:1', 'DAG 20:1-20:5', 'DAG 20:1-20:4', 'DAG 20:0-20:5', 'DAG 20:0-20:4', 'DAG 20:0-20:3', 'DAG 20:1-20:1', 'DAG 20:0-20:2', 'DAG 20:0-20:1', 'DAG 20:0-20:0', 'DAG 20:1-22:6', 'DAG 20:1-22:5', 'DAG 20:0-22:6', 'DAG 20:1-22:4', 'DAG 20:0-22:5', 'DAG 20:1-22:3', 'DAG 20:0-22:4', 'DAG 20:1-22:2', 'DAG 20:0-22:3', 'DAG 20:1-22:1', 'DAG 20:0-22:2', 'DAG 20:0-22:1', 'DAG 20:0-22:0', 'SM 34:2', 'SM 34:1', 'SM 34:0', 'SM 35:1', 'SM 35:0', 'SM 36:2', 'SM 36:1', 'SM 36:0', 'SM 37:1', 'SM 37:0', 'SM 38:2', 'SM 38:1', 'SM 38:0', 'SM 39:3', 'SM 39:2', 'SM 39:1', 'SM 40:6', 'SM 40:4', 'SM 40:3', 'SM 40:2', 'SM 40:1', 'SM 40:0', 'SM 41:4', 'SM 41:3', 'SM 41:2', 'SM 41:1', 'SM 42:5', 'SM 42:4', 'SM 42:3', 'SM 42:2', 'SM 42:1', 'TAG42:2-FA18:2', 'TAG42:2-FA12:0', 'TAG42:1-FA18:1', 'TAG42:1-FA16:0', 'TAG42:1-FA16:1', 'TAG42:1-FA14:0', 'TAG42:1-FA12:0', 'TAG42:0-FA16:0', 'TAG42:0-FA14:0', 'TAG42:0-FA12:0', 'TAG44:3-FA18:2', 'TAG44:2-FA18:1', 'TAG44:2-FA18:2', 'TAG44:2-FA16:0', 'TAG44:2-FA16:1', 'TAG44:2-FA14:0', 'TAG44:2-FA12:0', 'TAG44:1-FA18:1', 'TAG44:1-FA16:0', 'TAG44:1-FA16:1', 'TAG44:1-FA14:0', 'TAG44:1-FA14:1', 'TAG44:1-FA12:0', 'TAG44:0-FA18:0', 'TAG44:0-FA16:0', 'TAG44:0-FA14:0', 'TAG44:0-FA12:0', 'TAG45:1-FA18:1', 'TAG45:1-FA16:0', 'TAG45:1-FA15:0', 'TAG45:0-FA16:0', 'TAG45:0-FA15:0', 'TAG45:0-FA14:0', 'TAG46:4-FA18:2', 'TAG46:3-FA18:1', 'TAG46:3-FA18:2', 'TAG46:3-FA18:3', 'TAG46:3-FA16:0', 'TAG46:3-FA16:1', 'TAG46:3-FA14:0', 'TAG46:3-FA14:1', 'TAG46:3-FA12:0', 'TAG46:2-FA18:1', 'TAG46:2-FA18:2', 'TAG46:2-FA16:0', 'TAG46:2-FA16:1', 'TAG46:2-FA14:0', 'TAG46:2-FA14:1', 'TAG46:2-FA12:0', 'TAG46:1-FA18:0', 'TAG46:1-FA18:1', 'TAG46:1-FA16:0', 'TAG46:1-FA16:1', 'TAG46:1-FA14:0', 'TAG46:1-FA14:1', 'TAG46:1-FA12:0', 'TAG46:0-FA18:0', 'TAG46:0-FA16:0', 'TAG46:0-FA14:0', 'TAG46:0-FA12:0', 'TAG47:2-FA18:1', 'TAG47:2-FA18:2', 'TAG47:2-FA16:1', 'TAG47:2-FA15:0', 'TAG47:2-FA14:0', 'TAG47:1-FA18:1', 'TAG47:1-FA17:0', 'TAG47:1-FA16:0', 'TAG47:1-FA16:1', 'TAG47:1-FA15:0', 'TAG47:1-FA14:0', 'TAG47:0-FA17:0', 'TAG47:0-FA16:0', 'TAG47:0-FA15:0', 'TAG47:0-FA14:0', 'TAG48:5-FA18:3', 'TAG48:4-FA20:4', 'TAG48:4-FA18:1', 'TAG48:4-FA18:2', 'TAG48:4-FA18:3', 'TAG48:4-FA16:0', 'TAG48:4-FA16:1', 'TAG48:4-FA14:0', 'TAG48:4-FA14:1', 'TAG48:4-FA12:0', 'TAG48:3-FA18:1', 'TAG48:3-FA18:2', 'TAG48:3-FA18:3', 'TAG48:3-FA16:0', 'TAG48:3-FA16:1', 'TAG48:3-FA14:0', 'TAG48:3-FA14:1', 'TAG48:3-FA12:0', 'TAG48:2-FA18:0', 'TAG48:2-FA18:1', 'TAG48:2-FA18:2', 'TAG48:2-FA16:0', 'TAG48:2-FA16:1', 'TAG48:2-FA14:0', 'TAG48:2-FA14:1', 'TAG48:2-FA12:0', 'TAG48:1-FA18:0', 'TAG48:1-FA18:1', 'TAG48:1-FA16:0', 'TAG48:1-FA16:1', 'TAG48:1-FA14:0', 'TAG48:1-FA14:1', 'TAG48:0-FA18:0', 'TAG48:0-FA16:0', 'TAG48:0-FA14:0', 'TAG49:3-FA18:2', 'TAG49:3-FA18:3', 'TAG49:3-FA16:0', 'TAG49:3-FA16:1', 'TAG49:3-FA15:0', 'TAG49:2-FA18:1', 'TAG49:2-FA18:2', 'TAG49:2-FA17:0', 'TAG49:2-FA16:0', 'TAG49:2-FA16:1', 'TAG49:2-FA15:0', 'TAG49:2-FA14:0', 'TAG49:1-FA18:1', 'TAG49:1-FA17:0', 'TAG49:1-FA16:0', 'TAG49:1-FA16:1', 'TAG49:1-FA15:0', 'TAG49:1-FA14:0', 'TAG49:0-FA18:0', 'TAG49:0-FA17:0', 'TAG49:0-FA16:0', 'TAG49:0-FA15:0', 'TAG50:6-FA20:4', 'TAG50:5-FA20:4', 'TAG50:5-FA20:5', 'TAG50:5-FA18:1', 'TAG50:5-FA18:2', 'TAG50:5-FA18:3', 'TAG50:5-FA16:0', 'TAG50:5-FA16:1', 'TAG50:5-FA14:0', 'TAG50:4-FA20:3', 'TAG50:4-FA20:4', 'TAG50:4-FA18:1', 'TAG50:4-FA18:2', 'TAG50:4-FA18:3', 'TAG50:4-FA16:0', 'TAG50:4-FA16:1', 'TAG50:4-FA14:0', 'TAG50:4-FA14:1', 'TAG50:3-FA20:3', 'TAG50:3-FA18:0', 'TAG50:3-FA18:1', 'TAG50:3-FA18:2', 'TAG50:3-FA18:3', 'TAG50:3-FA16:0', 'TAG50:3-FA16:1', 'TAG50:3-FA14:0', 'TAG50:3-FA14:1', 'TAG50:2-FA20:2', 'TAG50:2-FA18:0', 'TAG50:2-FA18:1', 'TAG50:2-FA18:2', 'TAG50:2-FA16:0', 'TAG50:2-FA16:1', 'TAG50:2-FA14:0', 'TAG50:2-FA14:1', 'TAG50:1-FA20:1', 'TAG50:1-FA18:0', 'TAG50:1-FA18:1', 'TAG50:1-FA16:0', 'TAG50:0-FA18:0', 'TAG50:0-FA16:0', 'TAG50:0-FA14:0', 'TAG51:5-FA18:2', 'TAG51:4-FA20:4', 'TAG51:4-FA18:2', 'TAG51:4-FA18:3', 'TAG51:4-FA16:1', 'TAG51:4-FA15:0', 'TAG51:3-FA18:2', 'TAG51:3-FA18:3', 'TAG51:3-FA17:0', 'TAG51:3-FA16:1', 'TAG51:3-FA15:0', 'TAG51:2-FA18:1', 'TAG51:2-FA18:2', 'TAG51:2-FA17:0', 'TAG51:2-FA16:0', 'TAG51:2-FA16:1', 'TAG51:2-FA15:0', 'TAG51:1-FA18:0', 'TAG51:1-FA18:1', 'TAG51:1-FA17:0', 'TAG51:1-FA16:0', 'TAG51:1-FA15:0', 'TAG51:0-FA18:0', 'TAG52:6-FA22:6', 'TAG52:6-FA20:4', 'TAG52:6-FA20:5', 'TAG52:6-FA18:1', 'TAG52:6-FA18:2', 'TAG52:6-FA18:3', 'TAG52:6-FA16:0', 'TAG52:6-FA16:1', 'TAG52:6-FA14:0', 'TAG52:5-FA22:5', 'TAG52:5-FA20:3', 'TAG52:5-FA20:4', 'TAG52:5-FA20:5', 'TAG52:5-FA18:1', 'TAG52:5-FA18:2', 'TAG52:5-FA18:3', 'TAG52:5-FA16:0', 'TAG52:5-FA16:1', 'TAG52:5-FA14:0', 'TAG52:4-FA22:1', 'TAG52:4-FA22:4', 'TAG52:4-FA20:0', 'TAG52:4-FA20:2', 'TAG52:4-FA20:3', 'TAG52:4-FA20:4', 'TAG52:4-FA18:0', 'TAG52:4-FA18:1', 'TAG52:4-FA18:2', 'TAG52:4-FA18:3', 'TAG52:4-FA16:0', 'TAG52:4-FA16:1', 'TAG52:4-FA14:0', 'TAG52:3-FA22:1', 'TAG52:3-FA20:0', 'TAG52:3-FA20:1', 'TAG52:3-FA20:2', 'TAG52:3-FA20:3', 'TAG52:3-FA18:0', 'TAG52:3-FA18:1', 'TAG52:3-FA18:2', 'TAG52:3-FA16:0', 'TAG52:3-FA16:1', 'TAG52:3-FA14:0', 'TAG52:2-FA20:0', 'TAG52:2-FA20:1', 'TAG52:2-FA20:2', 'TAG52:2-FA18:0', 'TAG52:2-FA18:1', 'TAG52:2-FA18:2', 'TAG52:2-FA16:0', 'TAG52:2-FA16:1', 'TAG52:2-FA14:0', 'TAG52:1-FA20:0', 'TAG52:1-FA20:1', 'TAG52:1-FA16:1', 'TAG52:0-FA20:0', 'TAG52:0-FA18:0', 'TAG52:0-FA16:0', 'TAG53:6-FA20:4', 'TAG53:2-FA17:0', 'TAG53:2-FA16:0', 'TAG54:8-FA22:6', 'TAG54:8-FA20:4', 'TAG54:8-FA20:5', 'TAG53:1-FA18:0', 'TAG53:1-FA18:1', 'TAG54:8-FA18:2', 'TAG54:8-FA18:3', 'TAG53:1-FA17:0', 'TAG53:1-FA16:0', 'TAG53:0-FA16:0', 'TAG54:7-FA22:5', 'TAG54:7-FA22:6', 'TAG54:7-FA20:4', 'TAG54:7-FA20:5', 'TAG54:7-FA18:1', 'TAG54:7-FA18:2', 'TAG54:7-FA18:3', 'TAG54:7-FA16:1', 'TAG54:6-FA22:5', 'TAG54:6-FA22:6', 'TAG54:6-FA20:3', 'TAG54:6-FA20:4', 'TAG54:6-FA20:5', 'TAG54:6-FA18:1', 'TAG54:6-FA18:2', 'TAG54:6-FA18:3', 'TAG54:6-FA16:0', 'TAG54:6-FA16:1', 'TAG54:5-FA22:5', 'TAG54:5-FA22:1', 'TAG54:5-FA22:4', 'TAG54:5-FA20:2', 'TAG54:5-FA20:3', 'TAG54:5-FA20:4', 'TAG54:5-FA20:5', 'TAG54:5-FA18:0', 'TAG54:5-FA18:1', 'TAG54:5-FA18:2', 'TAG54:5-FA18:3', 'TAG54:5-FA16:0', 'TAG54:5-FA16:1', 'TAG54:4-FA22:1', 'TAG54:4-FA22:4', 'TAG54:4-FA20:1', 'TAG54:4-FA20:2', 'TAG54:4-FA20:3', 'TAG54:4-FA20:4', 'TAG54:4-FA18:0', 'TAG54:4-FA18:1', 'TAG54:4-FA18:2', 'TAG54:4-FA18:3', 'TAG54:4-FA16:0', 'TAG54:4-FA16:1', 'TAG54:3-FA20:1', 'TAG54:3-FA20:2', 'TAG54:1-FA20:0', 'TAG54:1-FA20:1', 'TAG54:1-FA18:0', 'TAG54:1-FA18:1', 'TAG54:1-FA16:0', 'TAG54:0-FA18:0', 'TAG54:0-FA16:0', 'TAG56:10-FA18:2', 'TAG56:9-FA22:6', 'TAG56:9-FA20:4', 'TAG56:9-FA20:5', 'TAG56:9-FA18:3', 'TAG56:8-FA22:5', 'TAG56:8-FA22:6', 'TAG56:8-FA20:4', 'TAG56:8-FA20:5', 'TAG56:8-FA18:1', 'TAG56:8-FA18:2', 'TAG56:8-FA18:3', 'TAG56:8-FA16:0', 'TAG56:8-FA16:1', 'TAG56:7-FA16:0', 'TAG56:7-FA22:4', 'TAG56:7-FA22:5', 'TAG56:7-FA22:6', 'TAG56:7-FA20:3', 'TAG56:7-FA20:4', 'TAG56:7-FA20:5', 'TAG56:7-FA18:0', 'TAG56:7-FA18:1', 'TAG56:7-FA18:2', 'TAG56:7-FA18:3', 'TAG56:7-FA16:1', 'TAG56:6-FA18:0', 'TAG56:6-FA18:1', 'TAG56:6-FA18:2', 'TAG56:6-FA18:3', 'TAG56:6-FA16:0', 'TAG56:6-FA22:4', 'TAG56:6-FA22:5', 'TAG56:6-FA20:2', 'TAG56:6-FA20:3', 'TAG56:6-FA20:4', 'TAG56:6-FA20:5', 'TAG56:5-FA22:4', 'TAG56:5-FA20:1', 'TAG56:5-FA20:2', 'TAG56:5-FA20:3', 'TAG56:5-FA20:4', 'TAG56:5-FA18:0', 'TAG56:5-FA18:1', 'TAG56:5-FA18:2', 'TAG56:5-FA16:0', 'TAG56:3-FA18:0', 'TAG56:3-FA18:1', 'TAG56:3-FA18:2', 'TAG56:3-FA16:0', 'TAG56:2-FA20:0', 'TAG56:2-FA20:1', 'TAG56:2-FA18:0', 'TAG56:2-FA16:0', 'TAG56:1-FA18:1', 'TAG56:1-FA16:0', 'TAG58:10-FA22:5', 'TAG58:10-FA22:6', 'TAG58:10-FA20:4', 'TAG58:10-FA20:5', 'TAG58:10-FA18:2', 'TAG58:9-FA18:1', 'TAG58:9-FA18:2', 'TAG58:9-FA22:5', 'TAG58:9-FA22:6', 'TAG58:9-FA20:4', 'TAG58:8-FA22:5', 'TAG58:8-FA22:6', 'TAG58:8-FA20:3', 'TAG58:8-FA20:4', 'TAG58:8-FA18:1', 'TAG58:8-FA18:2', 'TAG58:7-FA22:5', 'TAG58:7-FA20:4', 'TAG58:7-FA18:0', 'TAG58:7-FA18:1', 'TAG58:7-FA18:2', 'TAG58:7-FA22:6', 'TAG58:6-FA22:5', 'TAG58:6-FA18:0', 'TAG58:6-FA18:1', 'TAG58:6-FA16:0', 'TAG58:6-FA20:4', 'TAG58:3-FA18:1', 'TAG58:2-FA18:1', 'TAG60:12-FA22:6', 'TAG60:11-FA22:5', 'TAG60:11-FA22:6', 'TAG60:10-FA22:5', 'TAG60:10-FA22:6', 'LPE 14:0', 'LPE 15:0', 'LPE 16:1', 'LPE 16:0', 'LPE 17:1', 'LPE 17:0', 'LPE 18:3', 'LPE 18:2', 'LPE 18:1', 'LPE 18:0', 'LPE 19:1', 'LPE 19:0', 'LPE 20:5', 'LPE 20:4', 'LPE 20:3', 'LPE 20:2', 'LPE 20:1', 'LPE 20:0', 'LPE 22:6', 'LPE 22:2', 'LPE 22:1', 'LPE 22:0', 'LPC 14:0', 'LPC 15:0', 'LPC 16:1', 'LPC 16:0', 'LPC 17:1', 'LPC 17:0', 'LPC 18:3', 'LPC 18:2', 'LPC 18:1', 'LPC 18:0', 'LPC 19:1', 'LPC 19:0', 'LPC 20:5', 'LPC 20:4', 'LPC 20:3', 'LPC 20:2', 'LPC 20:1', 'LPC 20:0', 'LPC 22:6', 'LPC 22:5', 'LPC 22:4', 'LPC 22:2', 'LPC 22:1', 'LPC 22:0', 'PE 16:1-16:1', 'PE 16:0-16:1', 'PE 16:0-16:0', 'PE 16:1-18:4', 'PE 16:1-18:3', 'PE 16:0-18:4', 'PE 16:1-18:2', 'PE 16:0-18:3', 'PE 16:1-18:1', 'PE 16:0-18:2', 'PE 16:1-18:0', 'PE 16:0-18:1', 'PE 16:0-18:0', 'PE 17:0-17:0', 'PE 18:4-18:4', 'PE 18:3-18:4', 'PE 18:2-18:4', 'PE 16:1-20:5', 'PE 18:3-18:3', 'PE 16:1-20:4', 'PE 16:0-20:5', 'PE 18:2-18:3', 'PE 18:1-18:4', 'PE 16:1-20:3', 'PE 16:0-20:4', 'PE 18:2-18:2', 'PE 18:1-18:3', 'PE 18:0-18:4', 'PE 16:1-20:2', 'PE 16:0-20:3', 'PE 18:1-18:2', 'PE 18:0-18:3', 'PE 16:1-20:1', 'PE 16:0-20:2', 'PE 18:1-18:1', 'PE 18:0-18:2', 'PE 16:1-20:0', 'PE 16:0-20:1', 'PE 18:0-18:1', 'PE 16:0-20:0', 'PE 18:0-18:0', 'PE 18:4-20:5', 'PE 18:4-20:4', 'PE 18:3-20:5', 'PE 16:1-22:6', 'PE 18:4-20:3', 'PE 18:3-20:4', 'PE 18:2-20:5', 'PE 16:1-22:5', 'PE 16:0-22:6', 'PE 18:4-20:2', 'PE 18:3-20:3', 'PE 18:2-20:4', 'PE 18:1-20:5', 'PE 16:1-22:4', 'PE 18:4-20:1', 'PE 18:3-20:2', 'PE 18:2-20:3', 'PE 18:1-20:4', 'PE 18:0-20:5', 'PE 16:1-22:3', 'PE 16:0-22:4', 'PE 18:4-20:0', 'PE 18:3-20:1', 'PE 18:2-20:2', 'PE 18:1-20:3', 'PE 18:0-20:4', 'PE 16:1-22:2', 'PE 16:0-22:3', 'PE 18:3-20:0', 'PE 18:2-20:1', 'PE 18:1-20:2', 'PE 18:0-20:3', 'PE 16:1-22:1', 'PE 16:0-22:2', 'PE 18:2-20:0', 'PE 18:1-20:1', 'PE 18:0-20:2', 'PE 16:1-22:0', 'PE 16:0-22:1', 'PE 18:1-20:0', 'PE 18:0-20:1', 'PE 16:0-22:0', 'PE 18:0-20:0', 'PE 18:4-22:6', 'PE 20:5-20:5', 'PE 18:3-22:6', 'PE 20:4-20:5', 'PE 18:4-22:4', 'PE 18:3-22:5', 'PE 18:2-22:6', 'PE 20:4-20:4', 'PE 20:3-20:5', 'PE 18:4-22:3', 'PE 18:3-22:4', 'PE 18:2-22:5', 'PE 18:1-22:6', 'PE 20:3-20:4', 'PE 20:2-20:5', 'PE 18:3-22:3', 'PE 18:2-22:4', 'PE 18:1-22:5', 'PE 18:0-22:6', 'PE 18:4-22:1', 'PE 18:3-22:2', 'PE 18:2-22:3', 'PE 18:1-22:4', 'PE 18:0-22:5', 'PE 20:2-20:3', 'PE 20:1-20:4', 'PE 20:0-20:5', 'PE 18:4-22:0', 'PE 18:3-22:1', 'PE 18:2-22:2', 'PE 18:1-22:3', 'PE 18:0-22:4', 'PE 20:2-20:2', 'PE 20:1-20:3', 'PE 20:0-20:4', 'PE 18:3-22:0', 'PE 18:2-22:1', 'PE 18:1-22:2', 'PE 18:0-22:3', 'PE 20:1-20:2', 'PE 20:0-20:3', 'PE 18:2-22:0', 'PE 18:1-22:1', 'PE 18:0-22:2', 'PE 20:1-20:1', 'PE 20:0-20:2', 'PE 18:1-22:0', 'PE 18:0-22:1', 'PE 20:0-20:1', 'PE 18:0-22:0', 'PE 20:0-20:0', 'PE 20:5-22:6', 'PE 20:5-22:5', 'PE 20:4-22:6', 'PE 20:5-22:4', 'PE 20:4-22:5', 'PE 20:3-22:6', 'PE 20:5-22:3', 'PE 20:4-22:4', 'PE 20:3-22:5', 'PE 20:2-22:6', 'PE 20:5-22:2', 'PE 20:4-22:3', 'PE 20:3-22:4', 'PE 20:2-22:5', 'PE 20:1-22:6', 'PE 20:5-22:1', 'PE 20:4-22:2', 'PE 20:3-22:3', 'PE 20:2-22:4', 'PE 20:1-22:5', 'PE 20:0-22:6', 'PE 20:5-22:0', 'PE 20:4-22:1', 'PE 20:3-22:2', 'PE 20:2-22:3', 'PE 20:1-22:4', 'PE 20:0-22:5', 'PE 20:4-22:0', 'PE 20:3-22:1', 'PE 20:2-22:2', 'PE 20:1-22:3', 'PE 20:0-22:4', 'PE 20:3-22:0', 'PE 20:2-22:1', 'PE 20:1-22:2', 'PE 20:0-22:3', 'PE 20:2-22:0', 'PE 20:1-22:1', 'PE 20:0-22:2', 'PE 20:1-22:0', 'PE 20:0-22:1', 'PE 20:0-22:0', 'PE 22:6-22:6', 'PE 22:5-22:6', 'PE 22:5-22:5', 'PE 22:4-22:6', 'PE 22:4-22:5', 'PE 22:3-22:6', 'PE 22:4-22:4', 'PE 22:3-22:5', 'PE 22:2-22:6', 'PE 22:3-22:4', 'PE 22:2-22:5', 'PE 22:1-22:6', 'PE 22:3-22:3', 'PE 22:2-22:4', 'PE 22:1-22:5', 'PE 22:0-22:6', 'PE 22:2-22:3', 'PE 22:1-22:4', 'PE 22:0-22:5', 'PE 22:2-22:2', 'PE 22:1-22:3', 'PE 22:0-22:4', 'PE 22:1-22:2', 'PE 22:0-22:3', 'PE 22:1-22:1', 'PE 22:0-22:2', 'PE 22:0-22:1', 'PE 22:0-22:0', 'PG 18:2-18:2', 'PG 18:1-18:3', 'PG 18:0-18:4', 'PG 16:1-20:2', 'PG 16:0-20:3', 'PG 18:1-18:2', 'PG 18:0-18:3', 'PG 16:1-20:1', 

In [8]:
summary = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "n_missing": df.isna().sum(),
    "missing_rate": (df.isna().mean() * 100).round(2),
    "n_unique": df.nunique(dropna=True)
}).sort_values(["missing_rate", "n_unique"], ascending=[False, True])

display(summary)

                   dtype  n_missing  missing_rate  n_unique
PG 18:3-22:3     float64        376         96.41        13
PS 20:0-20:0     float64        374         95.90        15
PG 18:4-20:0     float64        370         94.87        17
PG 18:4-20:1     float64        369         94.62        17
PS 20:4-20:4     float64        369         94.62        20
...                  ...        ...           ...       ...
TAG54:0-FA16:0   float64          0          0.00       390
TAG56:10-FA18:2  float64          0          0.00       390
TAG56:2-FA20:0   float64          0          0.00       390
TAG56:2-FA16:0   float64          0          0.00       390
TAG58:3-FA18:1   float64          0          0.00       390

[1550 rows x 4 columns]

In [9]:
for i, c in enumerate(df.columns):
    print(i, repr(c))

0 'sample'
1 'O-Phosphoryl-ethanolamine'
2 'Acesulfame'
3 'Acetic acid'
4 'Propanoic acid'
5 'Glycolic acid'
6 'But-2-enoic acid'
7 'Valeric acid'
8 '2-Aminoisobutyric acid'
9 'L-Alpha-aminobutyric acid'
10 'alpha-Hydroxyisobutyric acid'
11 '2-Hydroxybutyric acid'
12 '3-Hydroxybutyric acid'
13 'Acetylglycine'
14 '3-Hydroxyisovaleric acid'
15 '2-Hydroxy-2-methylbutyric acid'
16 '5-Aminoimidazole-4-carboxamide'
17 'L-Pipecolic acid'
18 '4-Hydroxyproline'
19 'cis-4-Hydroxy-D-proline'
20 'Hydroxyisocaproic acid'
21 'Erythronic acid'
22 '2-Methylbenzoic acid'
23 'N-Methylnicotinamide'
24 '3,4-Dihydroxybenzaldehyde'
25 '2-Ethylhexanoic acid'
26 '2-Methylheptanoic Acid'
27 '4-Acetamidobutanoic acid'
28 '4-Guanidinobutyric acid'
29 'N,N-Dimethyl-L-Valine'
30 'Monomethyl glutaric acid'
31 '3-Methyloxindole'
32 '3,4-Dihydro-2H-1-benzopyran-2-one'
33 'D-Xylose'
34 'Hydrocinnamic acid'
35 '2-HYDROXY-4-(METHYLTHIO)BUTANOATE'
36 'Phenylglyoxylic acid'
37 'D-Arabinose'
38 '2-Phenylpropionic acid'
39 '2-Phenylglycine'
40 '(S)C(S)S-S-Methylcysteine sulfoxide'
41 '3-Hydroxyphenylacetic acid'
42 'Mandelic acid'
43 'Ribitol'
44 '3-Hydroxyanthranilic acid'
45 '3-Aminosalicylic acid'
46 'Gentisic acid'
47 'N-Acetylproline'
48 'Tranexamic Acid'
49 'Isovalerylglycine'
50 'Hydroxyoctanoic acid'
51 '2-Indolecarboxylic acid'
52 'S-Allylcysteine'
53 'Bicine'
54 '3-Phenylbutyric acid'
55 '2-Deoxyglucose'
56 '4-Hydroxycinnamic acid'
57 'm-Coumaric acid'
58 'L-Phenylalanine'
59 'Phenyllactic acid'
60 'Desaminotyrosine'
61 'Arabinonic acid'
62 'Vanillic acid'
63 'p-Hydroxymandelic acid'
64 '1-Methylhistidine'
65 'Decanoic acid'
66 'beta-Glycerophosphoric acid'
67 'N-Acetylleucine'
68 'Shikimic acid'
69 'Dehydroascorbic acid'
70 'Glycylvaline'
71 'L-Arginine'
72 'L-Gulonolactone'
73 'Glucosamine'
74 'D-Glucose'
75 'L-Sorbose'
76 'myo-Inositol'
77 'beta-(m-Hydroxyphenyl)hydracrylic Acid'
78 'Undecylenic acid'
79 'Phosphoserine'
80 'Undecanoic acid'
81 '3-Phosphoglyceric acid'
82 'Indoleacrylic acid'
83 'N-Acetylglutamine'
84 'L-Homoarginine'
85 '10-Hydroxydecanoic acid'
86 '3-Indoleglyoxylic acid'
87 'N-Acetyl-L-methionine'
88 '4-Aminohippuric acid'
89 'Ferulic acid'
90 '3-Hydroxyhippuric'
91 'D-Gluconolactone'
92 'Gluconic acid'
93 'Homoveratric acid'
94 'Selenomethionine'
95 'N-Acetyl-L-histidine'
96 'Syringic acid'
97 'Vanillymandelic Acid'
98 '5Z-Dodecenoic acid'
99 '11-Dodecenoic acid'
100 'Dodecanoic acid'
101 'Diethyl oxalpropionate'
102 '3-Indolebutyric acid'
103 'Indolepyruvate'
104 'L-Tryptophan'
105 'Xanthurenic acid'
106 'L-Kynurenine'
107 'Glyoxylic acid'
108 '12-Tridecanoic acid'
109 'Tridecanoic acid'
110 'N-a-Acetyl-L-arginine'
111 'Alanylglutamine'
112 'N-Acetyl-D-glucosamine'
113 'Oxalic acid'
114 'Cortisone'
115 'Myristoleic acid'
116 'Myristelaidic acid'
117 '3-Nitrotyrosine'
118 'Myristic acid'
119 '3,4,5-Trimethoxycinnamic acid'
120 "Pyridoxal 5'-phosphate"
121 'Maleic acid'
122 'Fumaric acid'
123 'Palmitoleic acid'
124 'Palmitelaidic acid'
125 '(7Z)-Hexadecenoic Acid'
126 '23-Nordeoxycholic Acid Methyl Ester'
127 'Alpha-N-Phenylacetyl-L-glutamine'
128 'Itaconic acid'
129 'Ketoleucine'
130 '3-Methyl-2-oxovaleric acid'
131 '2,3-Diphosphoglyceric acid'
132 'N-Acetyl-L-alanine'
133 'D-Aspartic acid'
134 'Inosine'
135 '10Z-Heptadecenoic acid'
136 '7-Ketolithocholic Acid Methyl Ester'
137 'cis,cis-Muconic acid'
138 'Urocanic acid'
139 'Alpha-Linolenic acid'
140 'Linolelaidic acid'
141 'Adipic acid'
142 'Methylglutaric acid'
143 'Oxoglutaric acid'
144 '2,2-Dimethylsuccinic acid'
145 '3,6-Diketocholanic Acid Ethyl Ester'
146 'N-Methyl-D-aspartic acid'
147 'CIS-11-OCTADECENOIC ACID'
148 'trans-Vaccenic acid'
149 'Petroselinic acid'
150 'Citramalic acid'
151 'Retinal'
152 'Tartaric acid'
153 '7-Dehydrocholic Acid Methyl Ester'
154 'Etodolac'
155 'Aspartame'
156 'Pimelic acid'
157 '3-Methyladipic acid'
158 '3-Oxoadipic acid'
159 '3,3-Dimethylglutaric acid'
160 'D-Ribulose'
161 '10Z-Nonadecenoic acid'
162 'Ricinoleic acid'
163 'all-trans-Retinoic acid'
164 '12-hydroxystearic acid'
165 'Phthalic acid'
166 'Quinolinic acid'
167 '2,6-Pyridinedicarboxylic acid'
168 'Eicosapentaenoic acid EPA'
169 '8Z,11Z,14Z,17Z-EICOSATETRAENOIC ACID'
170 'CIS-11,14,17-EICOSATRIENOIC ACID'
171 '8,11,14-Eicosatrienoic acid'
172 'Menadione'
173 '11C,14C-EICOSADIENOIC ACID'
174 'NANA'
175 'N-Acetylornithine'
176 '11Z-Eicosenoic acid'
177 'Citrulline'
178 'Ureidosuccinic acid'
179 'S-Carboxymethyl-L-cysteine'
180 '5beta-CHOLANIC ACID-3alpha, 7beta-DIOL N-(CARBOXYMETHYL)-AMIDE'
181 '4-Hydroxyphenylpyruvic acid'
182 'Etiadienic Acid'
183 'Pregnenolone'
184 'Etienic Acid'
185 '5beta-ANDROSTAN-3alpha-OL-17beta-CARBOXYLIC ACID'
186 '5beta-ANDROSTAN-3beta-OL-17beta-CARBOXYLIC ACID'
187 'Leucyl-Glycine'
188 "Uridine 5'-monophosphate"
189 'Kynurenic acid'
190 'N-carbamoylglutamic Acid'
191 'Docosahexaenoic acid DHA'
192 'Cyclic AMP'
193 'Docosapentaenoic acid DPA'
194 '5beta-CHOLANIC ACID-3alpha, 7alpha, 12alpha-TRIOL N-(CARBOXYMETHYL)-AMIDE'
195 'Etiadienic Acid Methyl Ester'
196 'Adrenic acid'
197 '5beta-ANDROSTAN-3-ONE-17beta-CARBOXYLIC ACID METHYL ESTER'
198 '4-ANDROSTEN-17alpha-OL-3-ONE-17beta-CARBOXYLIC ACID'
199 'Docosatrienoic acid'
200 '13C,16C-DOCOSADIENOIC ACID'
201 'Erucic acid'
202 '13tr-Docosenoic Acid'
203 'Isomaltose'
204 'Melibiose'
205 'Lactulose'
206 'Medroxyprogesterone'
207 'Glucaric acid'
208 'Galactaric acid'
209 '5beta-CHOLANIC ACID-12alpha-BROMO-3, 11-DIONE METHYL ESTER'
210 'Cytidine triphosphate'
211 'Etiadienic Acid 3-Acetate'
212 'Hydroretrocortine'
213 'Etienic Acid Acetate'
214 'Traumatic acid'
215 'Taurochenodeoxycholic Acid'
216 'Taurohyodeoxycholic Acid'
217 'Dodecanedioic acid'
218 '12-Ketolithocholic Acid Benzoate, Methyl Ester'
219 'Lithocholenic Acid'
220 'Lithocholic acid'
221 'ISOALLOLITHOCHOLIC ACID'
222 'Nordeoxycholic Acid'
223 'Tauro-omega-Muricholic Acid'
224 'Taurocholic acid'
225 'N-acetyltryptophan'
226 'Malonylcarnitine'
227 '3,6-Diketocholanic Acid'
228 '3,7-Diketocholanic Acid'
229 '12-Ketolithocholic acid'
230 'Beta-Ursodeoxycholic Acid'
231 'Beta-Hyodeoxycholic Acid'
232 'Chenodeoxycholic acid'
233 'Hyodeoxycholic acid'
234 'Murocholic acid'
235 'Ursodeoxycholic acid'
236 'Tetradecanedioic acid'
237 'Choleic Acid'
238 '23-Norcholic Acid'
239 'Dehydrocholic Acid'
240 'Dioxolithocholic Acid'
241 '7-Dehydrocholic acid'
242 'Cholic Acid'
243 'Beta-Muricholic Acid'
244 'Hyocholic acid'
245 'Ursocholic Acid'
246 'Heptacosanoic acid'
247 'Lithocholic Acid Acetate'
248 'O-Adipoylcarnitine'
249 'Oleoylcarnitine'
250 'Oxoadipic acid'
251 '1,2,3-Propanetricarboxylic acid'
252 'Glycodeoxycholic acid'
253 'Glycochenodeoxycholic acid'
254 'Glycoursodeoxycholic acid'
255 'Glycohyodeoxycholic Acid'
256 'Glycodehydrocholic Acid'
257 'Heneicosanoic acid'
258 'Citric acid'
259 'Isocitric acid'
260 '23-Norcholic Acid Diacetate'
261 '23-Nordeoxycholic Acid Diacetate'
262 'Glycocholic acid'
263 '2-Methylcitric acid'
264 '12-Dehydrocholic Acid Diacetate'
265 'Dehydrolithocholic acid'
266 'Taurocyamine'
267 'Diethyl tartrate'
268 'Glycine'
269 'Sarcosine'
270 'Beta-Alanine'
271 'L-Alanine'
272 'Dimethylglycine'
273 'Gamma-Aminobutyric acid'
274 'L-Serine'
275 'L-Proline'
276 'Cimetidine'
277 '4-Hydroxybenzoic acid'
278 'Indole-3-carboxaldehyde'
279 'L-Glutamine'
280 'L-Lysine'
281 'L-Methionine'
282 'Piperine'
283 'Ortho-Hydroxyphenylacetic acid'
284 'Protocatechuic acid'
285 'L-Histidine'
286 'Edetic Acid'
287 'Carnitine(C0)'
288 '7-Methylguanosine'
289 'Hippuric acid'
290 'Hydroxyphenyllactic acid'
291 'L-Homocitrulline'
292 '3-Indolepropionic acid'
293 'Salicyluric acid'
294 'L-Acetylcarnitine'
295 'Propionylcarnitine'
296 'Curcumin'
297 'Isovelarylcarnitine'
298 'Alpha-ketoisovaleric acid'
299 'L-Asparagine'
300 'Glutaric acid'
301 'N-Phenylacetylphenylalanine'
302 'Phenylpyrivic acid'
303 'N-Acetyl-L-aspartic acid'
304 'Decanoylcarnitine (C10)'
305 'Azelaic acid'
306 'Sebacic acid'
307 'Lauroylcarnitine'
308 'Adenosine monophosphate'
309 'Guanosine monophosphate'
310 'Myristoylcarnitine'
311 "s-(5'-Adenosyl)-L-homocysteine"
312 'Palmitoylcarnitine'
313 'Stearylcarnitine(C18)'
314 'Betaine'
315 'D-Xylulose'
316 'p-Hydroxyphenylacetic acid'
317 'L-Cysteic acid'
318 'Apocholic Acid'
319 '5beta-CHOLANIC ACID-3alpha, 7alpha, 12alpha-TRIOL 3-ETHOXYCARBONYL, METHYL ESTER'
320 'Estriol'
321 'Glycerol trihexanoate'
322 'Cer d18:1/22:0'
323 'Cer d18:1/24:1'
324 'Cer d18:1/24:0'
325 'DAG 16:0-16:1'
326 'DAG 16:0-16:0'
327 'DAG 16:1-18:4'
328 'DAG 16:1-18:3'
329 'DAG 16:1-18:2'
330 'DAG 16:0-18:3'
331 'DAG 16:1-18:1'
332 'DAG 16:0-18:2'
333 'DAG 16:0-18:1'
334 'DAG 16:0-18:0'
335 'DAG 18:1-18:4'
336 'DAG 18:1-18:3'
337 'DAG 18:1-18:2'
338 'DAG 18:0-18:3'
339 'DAG 18:1-18:1'
340 'DAG 18:0-18:2'
341 'DAG 18:0-18:1'
342 'DAG 18:0-18:0'
343 'DAG 18:1-20:5'
344 'DAG 18:1-20:4'
345 'DAG 18:1-20:3'
346 'DAG 18:1-20:2'
347 'DAG 18:1-20:1'
348 'DAG 20:1-20:5'
349 'DAG 20:1-20:4'
350 'DAG 20:0-20:5'
351 'DAG 20:0-20:4'
352 'DAG 20:0-20:3'
353 'DAG 20:1-20:1'
354 'DAG 20:0-20:2'
355 'DAG 20:0-20:1'
356 'DAG 20:0-20:0'
357 'DAG 20:1-22:6'
358 'DAG 20:1-22:5'
359 'DAG 20:0-22:6'
360 'DAG 20:1-22:4'
361 'DAG 20:0-22:5'
362 'DAG 20:1-22:3'
363 'DAG 20:0-22:4'
364 'DAG 20:1-22:2'
365 'DAG 20:0-22:3'
366 'DAG 20:1-22:1'
367 'DAG 20:0-22:2'
368 'DAG 20:0-22:1'
369 'DAG 20:0-22:0'
370 'SM 34:2'
371 'SM 34:1'
372 'SM 34:0'
373 'SM 35:1'
374 'SM 35:0'
375 'SM 36:2'
376 'SM 36:1'
377 'SM 36:0'
378 'SM 37:1'
379 'SM 37:0'
380 'SM 38:2'
381 'SM 38:1'
382 'SM 38:0'
383 'SM 39:3'
384 'SM 39:2'
385 'SM 39:1'
386 'SM 40:6'
387 'SM 40:4'
388 'SM 40:3'
389 'SM 40:2'
390 'SM 40:1'
391 'SM 40:0'
392 'SM 41:4'
393 'SM 41:3'
394 'SM 41:2'
395 'SM 41:1'
396 'SM 42:5'
397 'SM 42:4'
398 'SM 42:3'
399 'SM 42:2'
400 'SM 42:1'
401 'TAG42:2-FA18:2'
402 'TAG42:2-FA12:0'
403 'TAG42:1-FA18:1'
404 'TAG42:1-FA16:0'
405 'TAG42:1-FA16:1'
406 'TAG42:1-FA14:0'
407 'TAG42:1-FA12:0'
408 'TAG42:0-FA16:0'
409 'TAG42:0-FA14:0'
410 'TAG42:0-FA12:0'
411 'TAG44:3-FA18:2'
412 'TAG44:2-FA18:1'
413 'TAG44:2-FA18:2'
414 'TAG44:2-FA16:0'
415 'TAG44:2-FA16:1'
416 'TAG44:2-FA14:0'
417 'TAG44:2-FA12:0'
418 'TAG44:1-FA18:1'
419 'TAG44:1-FA16:0'
420 'TAG44:1-FA16:1'
421 'TAG44:1-FA14:0'
422 'TAG44:1-FA14:1'
423 'TAG44:1-FA12:0'
424 'TAG44:0-FA18:0'
425 'TAG44:0-FA16:0'
426 'TAG44:0-FA14:0'
427 'TAG44:0-FA12:0'
428 'TAG45:1-FA18:1'
429 'TAG45:1-FA16:0'
430 'TAG45:1-FA15:0'
431 'TAG45:0-FA16:0'
432 'TAG45:0-FA15:0'
433 'TAG45:0-FA14:0'
434 'TAG46:4-FA18:2'
435 'TAG46:3-FA18:1'
436 'TAG46:3-FA18:2'
437 'TAG46:3-FA18:3'
438 'TAG46:3-FA16:0'
439 'TAG46:3-FA16:1'
440 'TAG46:3-FA14:0'
441 'TAG46:3-FA14:1'
442 'TAG46:3-FA12:0'
443 'TAG46:2-FA18:1'
444 'TAG46:2-FA18:2'
445 'TAG46:2-FA16:0'
446 'TAG46:2-FA16:1'
447 'TAG46:2-FA14:0'
448 'TAG46:2-FA14:1'
449 'TAG46:2-FA12:0'
450 'TAG46:1-FA18:0'
451 'TAG46:1-FA18:1'
452 'TAG46:1-FA16:0'
453 'TAG46:1-FA16:1'
454 'TAG46:1-FA14:0'
455 'TAG46:1-FA14:1'
456 'TAG46:1-FA12:0'
457 'TAG46:0-FA18:0'
458 'TAG46:0-FA16:0'
459 'TAG46:0-FA14:0'
460 'TAG46:0-FA12:0'
461 'TAG47:2-FA18:1'
462 'TAG47:2-FA18:2'
463 'TAG47:2-FA16:1'
464 'TAG47:2-FA15:0'
465 'TAG47:2-FA14:0'
466 'TAG47:1-FA18:1'
467 'TAG47:1-FA17:0'
468 'TAG47:1-FA16:0'
469 'TAG47:1-FA16:1'
470 'TAG47:1-FA15:0'
471 'TAG47:1-FA14:0'
472 'TAG47:0-FA17:0'
473 'TAG47:0-FA16:0'
474 'TAG47:0-FA15:0'
475 'TAG47:0-FA14:0'
476 'TAG48:5-FA18:3'
477 'TAG48:4-FA20:4'
478 'TAG48:4-FA18:1'
479 'TAG48:4-FA18:2'
480 'TAG48:4-FA18:3'
481 'TAG48:4-FA16:0'
482 'TAG48:4-FA16:1'
483 'TAG48:4-FA14:0'
484 'TAG48:4-FA14:1'
485 'TAG48:4-FA12:0'
486 'TAG48:3-FA18:1'
487 'TAG48:3-FA18:2'
488 'TAG48:3-FA18:3'
489 'TAG48:3-FA16:0'
490 'TAG48:3-FA16:1'
491 'TAG48:3-FA14:0'
492 'TAG48:3-FA14:1'
493 'TAG48:3-FA12:0'
494 'TAG48:2-FA18:0'
495 'TAG48:2-FA18:1'
496 'TAG48:2-FA18:2'
497 'TAG48:2-FA16:0'
498 'TAG48:2-FA16:1'
499 'TAG48:2-FA14:0'
500 'TAG48:2-FA14:1'
501 'TAG48:2-FA12:0'
502 'TAG48:1-FA18:0'
503 'TAG48:1-FA18:1'
504 'TAG48:1-FA16:0'
505 'TAG48:1-FA16:1'
506 'TAG48:1-FA14:0'
507 'TAG48:1-FA14:1'
508 'TAG48:0-FA18:0'
509 'TAG48:0-FA16:0'
510 'TAG48:0-FA14:0'
511 'TAG49:3-FA18:2'
512 'TAG49:3-FA18:3'
513 'TAG49:3-FA16:0'
514 'TAG49:3-FA16:1'
515 'TAG49:3-FA15:0'
516 'TAG49:2-FA18:1'
517 'TAG49:2-FA18:2'
518 'TAG49:2-FA17:0'
519 'TAG49:2-FA16:0'
520 'TAG49:2-FA16:1'
521 'TAG49:2-FA15:0'
522 'TAG49:2-FA14:0'
523 'TAG49:1-FA18:1'
524 'TAG49:1-FA17:0'
525 'TAG49:1-FA16:0'
526 'TAG49:1-FA16:1'
527 'TAG49:1-FA15:0'
528 'TAG49:1-FA14:0'
529 'TAG49:0-FA18:0'
530 'TAG49:0-FA17:0'
531 'TAG49:0-FA16:0'
532 'TAG49:0-FA15:0'
533 'TAG50:6-FA20:4'
534 'TAG50:5-FA20:4'
535 'TAG50:5-FA20:5'
536 'TAG50:5-FA18:1'
537 'TAG50:5-FA18:2'
538 'TAG50:5-FA18:3'
539 'TAG50:5-FA16:0'
540 'TAG50:5-FA16:1'
541 'TAG50:5-FA14:0'
542 'TAG50:4-FA20:3'
543 'TAG50:4-FA20:4'
544 'TAG50:4-FA18:1'
545 'TAG50:4-FA18:2'
546 'TAG50:4-FA18:3'
547 'TAG50:4-FA16:0'
548 'TAG50:4-FA16:1'
549 'TAG50:4-FA14:0'
550 'TAG50:4-FA14:1'
551 'TAG50:3-FA20:3'
552 'TAG50:3-FA18:0'
553 'TAG50:3-FA18:1'
554 'TAG50:3-FA18:2'
555 'TAG50:3-FA18:3'
556 'TAG50:3-FA16:0'
557 'TAG50:3-FA16:1'
558 'TAG50:3-FA14:0'
559 'TAG50:3-FA14:1'
560 'TAG50:2-FA20:2'
561 'TAG50:2-FA18:0'
562 'TAG50:2-FA18:1'
563 'TAG50:2-FA18:2'
564 'TAG50:2-FA16:0'
565 'TAG50:2-FA16:1'
566 'TAG50:2-FA14:0'
567 'TAG50:2-FA14:1'
568 'TAG50:1-FA20:1'
569 'TAG50:1-FA18:0'
570 'TAG50:1-FA18:1'
571 'TAG50:1-FA16:0'
572 'TAG50:0-FA18:0'
573 'TAG50:0-FA16:0'
574 'TAG50:0-FA14:0'
575 'TAG51:5-FA18:2'
576 'TAG51:4-FA20:4'
577 'TAG51:4-FA18:2'
578 'TAG51:4-FA18:3'
579 'TAG51:4-FA16:1'
580 'TAG51:4-FA15:0'
581 'TAG51:3-FA18:2'
582 'TAG51:3-FA18:3'
583 'TAG51:3-FA17:0'
584 'TAG51:3-FA16:1'
585 'TAG51:3-FA15:0'
586 'TAG51:2-FA18:1'
587 'TAG51:2-FA18:2'
588 'TAG51:2-FA17:0'
589 'TAG51:2-FA16:0'
590 'TAG51:2-FA16:1'
591 'TAG51:2-FA15:0'
592 'TAG51:1-FA18:0'
593 'TAG51:1-FA18:1'
594 'TAG51:1-FA17:0'
595 'TAG51:1-FA16:0'
596 'TAG51:1-FA15:0'
597 'TAG51:0-FA18:0'
598 'TAG52:6-FA22:6'
599 'TAG52:6-FA20:4'
600 'TAG52:6-FA20:5'
601 'TAG52:6-FA18:1'
602 'TAG52:6-FA18:2'
603 'TAG52:6-FA18:3'
604 'TAG52:6-FA16:0'
605 'TAG52:6-FA16:1'
606 'TAG52:6-FA14:0'
607 'TAG52:5-FA22:5'
608 'TAG52:5-FA20:3'
609 'TAG52:5-FA20:4'
610 'TAG52:5-FA20:5'
611 'TAG52:5-FA18:1'
612 'TAG52:5-FA18:2'
613 'TAG52:5-FA18:3'
614 'TAG52:5-FA16:0'
615 'TAG52:5-FA16:1'
616 'TAG52:5-FA14:0'
617 'TAG52:4-FA22:1'
618 'TAG52:4-FA22:4'
619 'TAG52:4-FA20:0'
620 'TAG52:4-FA20:2'
621 'TAG52:4-FA20:3'
622 'TAG52:4-FA20:4'
623 'TAG52:4-FA18:0'
624 'TAG52:4-FA18:1'
625 'TAG52:4-FA18:2'
626 'TAG52:4-FA18:3'
627 'TAG52:4-FA16:0'
628 'TAG52:4-FA16:1'
629 'TAG52:4-FA14:0'
630 'TAG52:3-FA22:1'
631 'TAG52:3-FA20:0'
632 'TAG52:3-FA20:1'
633 'TAG52:3-FA20:2'
634 'TAG52:3-FA20:3'
635 'TAG52:3-FA18:0'
636 'TAG52:3-FA18:1'
637 'TAG52:3-FA18:2'
638 'TAG52:3-FA16:0'
639 'TAG52:3-FA16:1'
640 'TAG52:3-FA14:0'
641 'TAG52:2-FA20:0'
642 'TAG52:2-FA20:1'
643 'TAG52:2-FA20:2'
644 'TAG52:2-FA18:0'
645 'TAG52:2-FA18:1'
646 'TAG52:2-FA18:2'
647 'TAG52:2-FA16:0'
648 'TAG52:2-FA16:1'
649 'TAG52:2-FA14:0'
650 'TAG52:1-FA20:0'
651 'TAG52:1-FA20:1'
652 'TAG52:1-FA16:1'
653 'TAG52:0-FA20:0'
654 'TAG52:0-FA18:0'
655 'TAG52:0-FA16:0'
656 'TAG53:6-FA20:4'
657 'TAG53:2-FA17:0'
658 'TAG53:2-FA16:0'
659 'TAG54:8-FA22:6'
660 'TAG54:8-FA20:4'
661 'TAG54:8-FA20:5'
662 'TAG53:1-FA18:0'
663 'TAG53:1-FA18:1'
664 'TAG54:8-FA18:2'
665 'TAG54:8-FA18:3'
666 'TAG53:1-FA17:0'
667 'TAG53:1-FA16:0'
668 'TAG53:0-FA16:0'
669 'TAG54:7-FA22:5'
670 'TAG54:7-FA22:6'
671 'TAG54:7-FA20:4'
672 'TAG54:7-FA20:5'
673 'TAG54:7-FA18:1'
674 'TAG54:7-FA18:2'
675 'TAG54:7-FA18:3'
676 'TAG54:7-FA16:1'
677 'TAG54:6-FA22:5'
678 'TAG54:6-FA22:6'
679 'TAG54:6-FA20:3'
680 'TAG54:6-FA20:4'
681 'TAG54:6-FA20:5'
682 'TAG54:6-FA18:1'
683 'TAG54:6-FA18:2'
684 'TAG54:6-FA18:3'
685 'TAG54:6-FA16:0'
686 'TAG54:6-FA16:1'
687 'TAG54:5-FA22:5'
688 'TAG54:5-FA22:1'
689 'TAG54:5-FA22:4'
690 'TAG54:5-FA20:2'
691 'TAG54:5-FA20:3'
692 'TAG54:5-FA20:4'
693 'TAG54:5-FA20:5'
694 'TAG54:5-FA18:0'
695 'TAG54:5-FA18:1'
696 'TAG54:5-FA18:2'
697 'TAG54:5-FA18:3'
698 'TAG54:5-FA16:0'
699 'TAG54:5-FA16:1'
700 'TAG54:4-FA22:1'
701 'TAG54:4-FA22:4'
702 'TAG54:4-FA20:1'
703 'TAG54:4-FA20:2'
704 'TAG54:4-FA20:3'
705 'TAG54:4-FA20:4'
706 'TAG54:4-FA18:0'
707 'TAG54:4-FA18:1'
708 'TAG54:4-FA18:2'
709 'TAG54:4-FA18:3'
710 'TAG54:4-FA16:0'
711 'TAG54:4-FA16:1'
712 'TAG54:3-FA20:1'
713 'TAG54:3-FA20:2'
714 'TAG54:1-FA20:0'
715 'TAG54:1-FA20:1'
716 'TAG54:1-FA18:0'
717 'TAG54:1-FA18:1'
718 'TAG54:1-FA16:0'
719 'TAG54:0-FA18:0'
720 'TAG54:0-FA16:0'
721 'TAG56:10-FA18:2'
722 'TAG56:9-FA22:6'
723 'TAG56:9-FA20:4'
724 'TAG56:9-FA20:5'
725 'TAG56:9-FA18:3'
726 'TAG56:8-FA22:5'
727 'TAG56:8-FA22:6'
728 'TAG56:8-FA20:4'
729 'TAG56:8-FA20:5'
730 'TAG56:8-FA18:1'
731 'TAG56:8-FA18:2'
732 'TAG56:8-FA18:3'
733 'TAG56:8-FA16:0'
734 'TAG56:8-FA16:1'
735 'TAG56:7-FA16:0'
736 'TAG56:7-FA22:4'
737 'TAG56:7-FA22:5'
738 'TAG56:7-FA22:6'
739 'TAG56:7-FA20:3'
740 'TAG56:7-FA20:4'
741 'TAG56:7-FA20:5'
742 'TAG56:7-FA18:0'
743 'TAG56:7-FA18:1'
744 'TAG56:7-FA18:2'
745 'TAG56:7-FA18:3'
746 'TAG56:7-FA16:1'
747 'TAG56:6-FA18:0'
748 'TAG56:6-FA18:1'
749 'TAG56:6-FA18:2'
750 'TAG56:6-FA18:3'
751 'TAG56:6-FA16:0'
752 'TAG56:6-FA22:4'
753 'TAG56:6-FA22:5'
754 'TAG56:6-FA20:2'
755 'TAG56:6-FA20:3'
756 'TAG56:6-FA20:4'
757 'TAG56:6-FA20:5'
758 'TAG56:5-FA22:4'
759 'TAG56:5-FA20:1'
760 'TAG56:5-FA20:2'
761 'TAG56:5-FA20:3'
762 'TAG56:5-FA20:4'
763 'TAG56:5-FA18:0'
764 'TAG56:5-FA18:1'
765 'TAG56:5-FA18:2'
766 'TAG56:5-FA16:0'
767 'TAG56:3-FA18:0'
768 'TAG56:3-FA18:1'
769 'TAG56:3-FA18:2'
770 'TAG56:3-FA16:0'
771 'TAG56:2-FA20:0'
772 'TAG56:2-FA20:1'
773 'TAG56:2-FA18:0'
774 'TAG56:2-FA16:0'
775 'TAG56:1-FA18:1'
776 'TAG56:1-FA16:0'
777 'TAG58:10-FA22:5'
778 'TAG58:10-FA22:6'
779 'TAG58:10-FA20:4'
780 'TAG58:10-FA20:5'
781 'TAG58:10-FA18:2'
782 'TAG58:9-FA18:1'
783 'TAG58:9-FA18:2'
784 'TAG58:9-FA22:5'
785 'TAG58:9-FA22:6'
786 'TAG58:9-FA20:4'
787 'TAG58:8-FA22:5'
788 'TAG58:8-FA22:6'
789 'TAG58:8-FA20:3'
790 'TAG58:8-FA20:4'
791 'TAG58:8-FA18:1'
792 'TAG58:8-FA18:2'
793 'TAG58:7-FA22:5'
794 'TAG58:7-FA20:4'
795 'TAG58:7-FA18:0'
796 'TAG58:7-FA18:1'
797 'TAG58:7-FA18:2'
798 'TAG58:7-FA22:6'
799 'TAG58:6-FA22:5'
800 'TAG58:6-FA18:0'
801 'TAG58:6-FA18:1'
802 'TAG58:6-FA16:0'
803 'TAG58:6-FA20:4'
804 'TAG58:3-FA18:1'
805 'TAG58:2-FA18:1'
806 'TAG60:12-FA22:6'
807 'TAG60:11-FA22:5'
808 'TAG60:11-FA22:6'
809 'TAG60:10-FA22:5'
810 'TAG60:10-FA22:6'
811 'LPE 14:0'
812 'LPE 15:0'
813 'LPE 16:1'
814 'LPE 16:0'
815 'LPE 17:1'
816 'LPE 17:0'
817 'LPE 18:3'
818 'LPE 18:2'
819 'LPE 18:1'
820 'LPE 18:0'
821 'LPE 19:1'
822 'LPE 19:0'
823 'LPE 20:5'
824 'LPE 20:4'
825 'LPE 20:3'
826 'LPE 20:2'
827 'LPE 20:1'
828 'LPE 20:0'
829 'LPE 22:6'
830 'LPE 22:2'
831 'LPE 22:1'
832 'LPE 22:0'
833 'LPC 14:0'
834 'LPC 15:0'
835 'LPC 16:1'
836 'LPC 16:0'
837 'LPC 17:1'
838 'LPC 17:0'
839 'LPC 18:3'
840 'LPC 18:2'
841 'LPC 18:1'
842 'LPC 18:0'
843 'LPC 19:1'
844 'LPC 19:0'
845 'LPC 20:5'
846 'LPC 20:4'
847 'LPC 20:3'
848 'LPC 20:2'
849 'LPC 20:1'
850 'LPC 20:0'
851 'LPC 22:6'
852 'LPC 22:5'
853 'LPC 22:4'
854 'LPC 22:2'
855 'LPC 22:1'
856 'LPC 22:0'
857 'PE 16:1-16:1'
858 'PE 16:0-16:1'
859 'PE 16:0-16:0'
860 'PE 16:1-18:4'
861 'PE 16:1-18:3'
862 'PE 16:0-18:4'
863 'PE 16:1-18:2'
864 'PE 16:0-18:3'
865 'PE 16:1-18:1'
866 'PE 16:0-18:2'
867 'PE 16:1-18:0'
868 'PE 16:0-18:1'
869 'PE 16:0-18:0'
870 'PE 17:0-17:0'
871 'PE 18:4-18:4'
872 'PE 18:3-18:4'
873 'PE 18:2-18:4'
874 'PE 16:1-20:5'
875 'PE 18:3-18:3'
876 'PE 16:1-20:4'
877 'PE 16:0-20:5'
878 'PE 18:2-18:3'
879 'PE 18:1-18:4'
880 'PE 16:1-20:3'
881 'PE 16:0-20:4'
882 'PE 18:2-18:2'
883 'PE 18:1-18:3'
884 'PE 18:0-18:4'
885 'PE 16:1-20:2'
886 'PE 16:0-20:3'
887 'PE 18:1-18:2'
888 'PE 18:0-18:3'
889 'PE 16:1-20:1'
890 'PE 16:0-20:2'
891 'PE 18:1-18:1'
892 'PE 18:0-18:2'
893 'PE 16:1-20:0'
894 'PE 16:0-20:1'
895 'PE 18:0-18:1'
896 'PE 16:0-20:0'
897 'PE 18:0-18:0'
898 'PE 18:4-20:5'
899 'PE 18:4-20:4'
900 'PE 18:3-20:5'
901 'PE 16:1-22:6'
902 'PE 18:4-20:3'
903 'PE 18:3-20:4'
904 'PE 18:2-20:5'
905 'PE 16:1-22:5'